// generated by yuc

// --nostdlib option was passed

// MetalLib (Aku Self-Contained Runtime Library)
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

int strlen(char* str) {
    int len = 0;
    while(str[len])
        len++;
    return len;
}

void* memmove(void* dstptr,  void* srcptr, uint64_t size) {
    uint8_t* dst = (uint8_t*) dstptr;
	uint8_t* src = (uint8_t*) srcptr;
	if (dst < src) {
		for (uint64_t i = 0; i < size; i++)
			dst[i] = src[i];
	} else {
		for (uint64_t i = size; i != 0; i--)
			dst[i-1] = src[i-1];
	}
	return dstptr;
}

int memcmp(void* aptr, void* bptr, uint64_t size) {
	uint8_t* a = (uint8_t*) aptr;
	uint8_t* b = (uint8_t*) bptr;
	for (uint64_t i = 0; i < size; i++) {
		if (a[i] < b[i])
			return -1;
		else if (b[i] < a[i])
			return 1;
	}
	return 0;
}

void* memset(void* bufptr, int value, uint64_t size) {
	uint8_t* buf = (uint8_t*) bufptr;
	for (uint64_t i = 0; i < size; i++)
		buf[i] = (uint8_t) value;
	return bufptr;
}

void* memcpy(void* dstptr, void* restrict srcptr, uint64_t size) {
	uint8_t* dst = (uint8_t*) dstptr;
	uint64_t* src = (uint64_t*) srcptr;
	for (uint64_t i = 0; i < size; i++)
		dst[i] = src[i];
	return dstptr;
}


// built-in type names
#include <stdint.h>
typedef int8_t  int8;       // 8 bit integer
typedef int16_t int16;      // 16 bit integer
typedef int32_t int32;      // 32 bit integer
typedef int64_t int64;      // 64 bit integer
typedef uint8_t uint8;      // 8 bit unsigned integer
typedef uint16_t uint16;    // 16 bit unsigned integer
typedef uint32_t uint32;    // 32 bit unsigned integer
typedef uint64_t uint64;    // 64 bit unsigned integer
typedef char **stringp;     // char**
// user headers
#include "stdio.h"
#include "stdlib.h"



int main(int argc, stringp argv){
if(argc==1){
printf("usage: %s [echo]\n", argv[0]);
exit(0);
} else if(argc==2){
printf("%s\n", argv[1]);
} else {
printf("%s\n", join(' ', argv));
}
return 0;
}


