// generated by yuc


// Aku std library
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

typedef FILE *file;

char* readfile(char* path, char* mode) {
    file f;

    if(mode == NULL) {
        f = fopen(path, "rb");
    } else {
        f = fopen(path, mode);
    }

    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);

    char* buffer = malloc(fsize + 1);
    fread(buffer, 1, fsize, f);
    fclose(f);

    buffer[fsize] = 0;
    return buffer;
}


// built-in type names
#include <stdint.h>
typedef int8_t  int8;       // 8 bit integer
typedef int16_t int16;      // 16 bit integer
typedef int32_t int32;      // 32 bit integer
typedef int64_t int64;      // 64 bit integer
typedef uint8_t uint8;      // 8 bit unsigned integer
typedef uint16_t uint16;    // 16 bit unsigned integer
typedef uint32_t uint32;    // 32 bit unsigned integer
typedef uint64_t uint64;    // 64 bit unsigned integer
typedef char **stringp;     // char**
// user headers
#include "stdio.h"
#include "stdlib.h"



int main(int argc, stringp argv){
printf("%s\n", argv[0]);
return 0;
}


