// generated by yuc


// Aku std library
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

typedef FILE *file;

char* readfile(char* path, char* mode) {
    file f;

    if(mode == NULL) {
        f = fopen(path, "rb");
    } else {
        f = fopen(path, mode);
    }

    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);

    char* buffer = malloc(fsize + 1);
    fread(buffer, 1, fsize, f);
    fclose(f);

    buffer[fsize] = 0;
    return buffer;
}

char* join(char delim, char** strs) {
    char* res = calloc(128, sizeof(char));
    char* c;
    char sep[2] = { delim, 0 };
    int i = 0;
    for (c = strs[i]; c; c = strs[++i]) {
        strcat(res, c);
        strcat(res, sep);
    }
    return res;
}


// built-in type names
#include <stdint.h>
typedef int8_t  int8;       // 8 bit integer
typedef int16_t int16;      // 16 bit integer
typedef int32_t int32;      // 32 bit integer
typedef int64_t int64;      // 64 bit integer
typedef uint8_t uint8;      // 8 bit unsigned integer
typedef uint16_t uint16;    // 16 bit unsigned integer
typedef uint32_t uint32;    // 32 bit unsigned integer
typedef uint64_t uint64;    // 64 bit unsigned integer
typedef char **stringp;     // char**
// user headers
#include "stdio.h"



int main(int argc, stringp argv){
int xx = 17<<8;
int yy = 00;
int xxyy = xx|yy;
int xx2 = xxyy&65280;
printf("0x%x\n", xx2>>8);
if(xx==4352&&xx2==17){
printf("xx is correct :)\n");
}
return 0;
}


