// generated by yuc


// Aku std library
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

typedef FILE *file;

char* readfile(char* path, char* mode) {
    file f;

    if(mode == NULL) {
        f = fopen(path, "rb");
    } else {
        f = fopen(path, mode);
    }

    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);

    char* buffer = malloc(fsize + 1);
    fread(buffer, 1, fsize, f);
    fclose(f);

    buffer[fsize] = 0;
    return buffer;
}

char* join(char delim, char** strs) {
    char* res = calloc(128, sizeof(char));
    char* c;
    char sep[2] = { delim, 0 };
    int i = 0;
    for (c = strs[i]; c; c = strs[++i]) {
        strcat(res, c);
        strcat(res, sep);
    }
    return res;
}

int print(char* restrict format, ...) {
    int written = 0;
    va_list parameters;
    va_start(parameters, format);
    written = printf(format, parameters);
    va_end(parameters);
    return written;
}

int println(char* format, ...) {
    int written = 0;
    va_list parameters;
    va_start(parameters, format);
    format = realloc(format, (strlen(format) + 1) * sizeof(char));
    strcat(format, "\n");
    written = printf(format, parameters);
    va_end(parameters);
    return written;
}


// built-in type names
#include <stdint.h>
typedef int8_t  int8;       // 8 bit integer
typedef int16_t int16;      // 16 bit integer
typedef int32_t int32;      // 32 bit integer
typedef int64_t int64;      // 64 bit integer
typedef uint8_t uint8;      // 8 bit unsigned integer
typedef uint16_t uint16;    // 16 bit unsigned integer
typedef uint32_t uint32;    // 32 bit unsigned integer
typedef uint64_t uint64;    // 64 bit unsigned integer
typedef char **stringp;     // char**
// user headers
#include "stdio.h"



struct Magic {
	char* name;
	uint8 byte;
};
typedef struct Magic magic_t;
char hi(){
return 50;
}
int main(int argc, stringp argv){
magic_t test = { "BIG MAN", 25 };
printf("test.name = %s\n", test.name);
printf("hi(): %c\n", hi());
if(1!=1){
printf("yes.\n");
} else if(1>2){
printf("maybe.\n");
} else if(1==3){
printf("probably not.\n");
} else {
printf("no.\n");
}
int count = 0;
while(count!=2){
printf("in a while loop! iteration: %d\n", count);
count = count+1;
}
printf("merge xx and yy into xxyy:\n");
int xx = 17<<8;
printf("xx = 0x%02x\n", xx>>8);
int yy = 00;
printf("yy = 0x%02x\n", yy);
int xxyy = xx|yy;
printf("xxyy = 0x%04x\n", xxyy);
if(1==2||1==1){
printf("logical or\n");
} else {
printf("hm yes won't reach me ;)\n");
}
if(1==1&&1==2){
printf("won't reach me ;)\n");
} else {
printf("logical and! (because && requires both sides to evaluate to true and 1 isn't equal to 2)\n");
}
printf("args: %s\n", join(' ', argv));
float db = 1.0;
printf("floats! %f\n", db);
println("test!");
return 0;
}


